CREATE TABLE IF NOT EXISTS keyword (
    id bigint NOT NULL PRIMARY KEY AUTO_INCREMENT,
    keyword VARCHAR(100) NOT NULL,
    count INT(11) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
ENGINE = InnoDB;
